### ISSUE TITLE
example make error

### ISSUE THREAD

**Issue by alexhilaev** [nthu-pllab/RISCV-DLR#2]
when i try to "make" an example, it gives me 
`Traceback (most recent call last):
  File "build_module.py", line 5, in <module>
    import tvm
ImportError: No module named tvm`

**Comment by JarvisRu** [comment]
Hi @alexhilaev! Thank you for asking.
As this project is based on TVM, the first thing you need to do is to make sure your env has TVM (we used v0.6) for compiling and optimizing AI models. For more details, please refer to [TVM](https://tvm.apache.org/) directly. And for the real showcase with this runtime, since we haven't submitted our source code of TVM that optimizes QNN for RISC-V with P extension, you can't run it directly with our sample code. It's only for demonstrating how we run and optimize for the entire flow.
But if you only want to try this runtime with a simple AI model with TVM to RISC-V (without codegen with special extension - V, P extension). We may be able to generate a sample code if you need.

**Comment by alexhilaev** [comment]
yeah, i understand now. i`m closing it, sorry for disturbing.
